{{- if .Values.postgres.enabled }}
{{- with .Values.postgres }}
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ .name }}-postgres
  namespace: {{ $.Release.Namespace }}
spec:
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.2.1
  instances: 1

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  managed:
    roles:
      - name: immich
        superuser: true
        login: true

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    size: 4Gi
    storageClass: local-path
{{- end }}
{{- end }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: immich-postgres-user
  namespace: {{ $.Release.Namespace }}
data:
  user: {{ .Values.postgres.user | b64enc }}
  password: {{ .Values.postgres.password | b64enc }}