{{- if .Values.pv.createPvc }}
{{- with .Values.pv }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .name }}-pvc
  namespace: {{ $.Release.Namespace }}
spec:
  volumeName: {{ .name }}-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: nfs-csi
{{- end }}
{{- end }}