apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-pv
spec:
  storageClassName: jellyfin-sc
  claimRef:
    name: jellyfin-pvc
    namespace: jellyfin
  csi:
    driver: nfs.csi.k8s.io
    readOnly: false
    volumeAttributes:
      server: 192.168.1.100
      share: /mnt/store/media
    volumeHandle: truenas/jellyfin
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nfsvers=4.1
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-pvc
  namespace: jellyfin
spec:
  volumeName: jellyfin-pv
  accessModes:
    - ReadWriteMany
  storageClassName: jellyfin-sc
  resources:
    requests:
      storage: 1Ti