apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homepage
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: homepage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      enabled: true
  sources:
  - repoURL: https://github.com/jerryyf/home-ops.git
    targetRevision: main
    path: apps/homepage