apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jellyfin
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: jellyfin
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      enabled: true
  sources:
  - repoURL: https://github.com/jerryyf/home-ops.git
    targetRevision: main
    path: apps/jellyfin
  - repoURL: https://jellyfin.github.io/jellyfin-helm
    chart: jellyfin
    targetRevision: 3.2.0
    helm:
      values: |
        persistence:
          media:
            storageClass: jellyfin-sc
            size: 1Ti
            existingClaim: jellyfin-pvc
        nodeSelector:
          kubernetes.io/hostname: k3s-worker-1