apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-pg
  namespace: immich
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-standard-trixie
  instances: 1
  storage:
    size: 8Gi
  postgresql:
    shared_preload_libraries:
    - vchord.so
  bootstrap:
    initdb:
      postInitSQL:
      - "CREATE EXTENSION IF NOT EXISTS vchord CASCADE;"
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich
  namespace: immich
spec:
  name: app
  owner: app
  cluster:
    name: immich-pg
  extensions:
  - name: vchord
    ensure: present