---
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    ports:
      immich:
        port: 2283
        expose: true
        exposedPort: 2283
        protocol: TCP