apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: immich
  namespace: immich
  annotations: {}
spec:
  ingressClassName: traefik
  defaultBackend:
    service:
      name: immich-server
      port:
        number: 2283