{{- range .Values.apps }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .name }}-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - {{ .hostname }}
    port:
      name: http
      number: 80
      protocol: HTTP
  - hosts:
    - {{ .hostname }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .name }}-tls
---
{{- end }}