{{- range .Values.apps }}
{{- if .ingress }}
apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: {{ .name }}-gateway
  namespace: {{ .namespace }}
spec:
  selector:
    istio: ingress
  servers:
  - hosts:
    - {{ .hostname }}
    port:
      name: http
      number: 80
      protocol: HTTP
  {{- if .tls }}
  - hosts:
    - {{ .hostname }}
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: {{ .name }}-tls
  {{- end }}
---
{{- end }}
{{- end }}
