{{- range .Values.apps }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .name }}-virtualservice
  namespace: istio-system
spec:
  gateways:
  - {{ .name }}-gateway
  hosts:
  - {{ .hostname }}
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: {{ .dest }}
        port:
          number: {{ .port }}
---
{{- end }}