{{- range .Values.apps }}
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ .name }}-virtualservice
  namespace: {{ .namespace }}
spec:
  gateways:
  - {{ .name }}-gateway
  hosts:
  - {{ .hostname }}
  http:
  - match:
    - uri:
        prefix: {{ .path }}
    route:
    - destination:
        host: {{ .dest.fqdn }}
        port:
          number: {{ .dest.port }}
---
{{- end }}