apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-token
  namespace: cloudflared
spec:
  encryptedData:
    token: AgByI6XYZTXrnkT/iMosYyPzl99LX9GaUCALxq2R0YlyPtm5B/3ayC1Yp0ACsxpM09wfa5WsYepvfKxahSH8aLy7PbQeD0gE2PrxUzn89ds+05wsOZxzESdYAhK8T1BepjqjVExuWNPsM6RpiuHGJds6AMBGEwV1xCsKVO7wx3fAQVChHciCJRuPM/4GilBw4LAkSkaDfsko+1mEBSh8Z+ylI9WPkxZXJLdstYFz89sONMzr40Wgt5Ay+DJDa53R033sJz1kSThkigk/0j6C3vW3IpUKXXZJgygmvR5BpE1GU5hL2FAUnbASurJdwkcauZ4ieEvDT7uLPFBQMOJlJ1/bRwnEYtNx95HCpsh83eqs2SiOwUdn2U0zlnKw9GUwnvcq6B0QHmzdRBkhBz5WVGe6OTOtngcbR/urH6pjb7iRnLPlBk25IUuorx0zgyFjEOgq621xdsm93oPECjhHdcvqEmFZm69bhgveV4QLsgFt1yk30vr1AA7c1r8ug7xCzyUfmx/ZgfZeq1/XyqtGDQDoNdIb35DUvJJibHAnI6Inz0ZSdvXn8WJXMQMq/YG90DJr0R5bceuVzCzOVbak3womkvaAt9lu2E+2y15a5CuFJHShkAiO173IRtro9uF5MbRrXe1fDyhsjPYnA5SBFdkqOwA1mm0udkYtEfa36+mtTNAznzRIZHEaJRYk1LjdsgfgGA/kTvg3j59Zo5PmP636BPymE12AYQCpj/rCz5bOr5hxtNx66oitNtIx2EW57+4oK0XZFqbIrDtRcS69r+DnFoYi+0nJYs0znqHNSGBXKWOxebhDLwC4uK8MvNV4HS+GDk20uGjuvayc7xn6BvTS8j0IwR+V7d8sM8+SICAGBxgUGzMd6PJ1+4bY1lY8sgcOLqa5blMtlPjRqaICbBqI+/pq2ZampOa3JjcP5pTkGFJ3CEqnmj3b
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      name: tunnel-token
      namespace: cloudflared

