apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-pv
  namespace: {{ .Release.Namespace }}
spec:
  capacity:
    storage: 512Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-csi
  mountOptions:
    - nfsvers=4.1
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: {{ .Values.nfs.volumeHandle }}
    volumeAttributes:
      server: {{ .Values.nfs.server }}
      share: {{ .Values.nfs.share }}