apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-pvc
  namespace: {{ .Release.Namespace }}
spec:
  volumeName: immich-pv
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 512Gi
  storageClassName: nfs-csi
